badword:
  '@agwg18': ''
  '@agwg_pub': ''
channel_id: null
group_ids:
- 183544192
groups:
  -183544192:
    channels:
    - -1001790441419
    last_post: 1976
  -152642241:
    channels:
    - -1001950063455
    last_post: 52832
tg_bot: 6655280532:AAEGujrUvGmJ9t8WRuc_xV6JZP_6Z84JqY4 #AGWG18-BOT
tgph:
  name: AGWG_POST
  token: #AUTOMATIC
vk:
  login: 
  password: 
