version: "3"

services:
  teavk:
    image: ghcr.io/kaiyga/teavk:teavkbot-latest
    container_name: teavkbot
    volumes:
      - ./config.yml:/home/teavk/config.yml
    restart: unless-stopped

  # teavk:
  #   build : 
  #     context: ./
  #     dockerfile: Dockerfile
  #   container_name: teavkbot_selfbuild
  #   environment:
  #     - USER_UID=1000
  #     - USER_GID=1000
  #   volumes:
  #     - ./config.yml:/home/teavk/config.yml
  #   restart: unless-stopped
